spring.application.name=NordFlow-auth-service

## Database connection enviromental details ##
spring.datasource.url=jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/nordflow_auth
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${SERVER_PORT}

## For the JPA Database
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# no lazy loading in the controllers, keeps db connections short
spring.jpa.open-in-view=false

## For the Flyway
spring.flyway.enabled=true
