spring.application.name=NordFlow-auth-service

## Connection to the Database itself ##
spring.datasource.url=${DB.URL}
spring.datasource.username=${DB.USERNAME}
spring.datasource.password=${DB.PASSWORD}
server.port=${DB.PORT}

## Settings for the database like validate ##
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

## For Flyway ##
spring.flyway.enabled=true